'use client'

import dynamic from 'next/dynamic'
import { useEffect, useMemo, useRef, useState } from 'react'
import { outputUrl, outputHtmlUrl } from '@/lib/lab/llm-benchmark/nav'
import { withPrelude } from '@/lib/lab/llm-benchmark/frame-prelude'
import { AlertCircle, ExternalLink, Loader2, Play } from 'lucide-react'

interface ArtifactFrameProps {
  /** Benchmark task id, e.g. "n-body-field" (lib/lab/llm-benchmark/registry). */
  taskId: string
  /** Benchmark model id, e.g. "kimi-k3". */
  modelId: string
  /** Content-hash cache-buster (BenchmarkResultMeta.outputVersion); optional. */
  version?: string
  /** Small mono header above the frame. */
  title?: string
  /** Figcaption text, shown beside the "Open full page" link. */
  caption?: string
  /** Frame height in px (default 480). */
  height?: number
}

type LoadState =
  | { phase: 'idle' }
  | { phase: 'loading' }
  | { phase: 'ready'; output: string }
  | { phase: 'error'; message: string }

function ArtifactFrameInner({
  taskId,
  modelId,
  version,
  title,
  caption,
  height = 480,
}: ArtifactFrameProps) {
  const [state, setState] = useState<LoadState>({ phase: 'idle' })
  const seq = useRef(0)

  async function run() {
    const id = ++seq.current
    setState({ phase: 'loading' })
    try {
      const res = await fetch(outputUrl(taskId, modelId, version), { cache: 'force-cache' })
      if (!res.ok) throw new Error(`HTTP ${res.status}`)
      const data = (await res.json()) as { output?: string }
      if (id !== seq.current) return // a newer request superseded this one
      if (!data.output) throw new Error('empty output')
      setState({ phase: 'ready', output: data.output })
    } catch (err) {
      if (id !== seq.current) return
      setState({ phase: 'error', message: err instanceof Error ? err.message : 'failed to load' })
    }
  }

  // Auto-run on mount — except when the visitor prefers reduced motion, where
  // we leave a play gate so they opt in to the canvas/WebGL animation instead
  // of it starting under them (mirrors GeneratedDemo).
  useEffect(() => {
    const reduce =
      typeof window !== 'undefined' &&
      window.matchMedia?.('(prefers-reduced-motion: reduce)').matches
    if (!reduce) run()
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [taskId, modelId, version])

  // srcdoc rather than a blob: URL or a direct link: Safari won't run scripts
  // in a blob-URL sandboxed frame, and the site CSP's frame-src blocks iframe
  // URLs outright. An inline srcdoc at an opaque origin works everywhere.
  const frameDoc = useMemo(
    () => (state.phase === 'ready' ? withPrelude(state.output) : undefined),
    [state],
  )

  return (
    <figure className="m-0">
      <div className="overflow-hidden rounded-xl border border-[var(--color-border)] bg-[#0c0c10]">
        {title && (
          <div className="border-b border-white/10 px-4 py-2.5 font-mono text-xs uppercase tracking-wider text-white/60">
            {title}
          </div>
        )}
        <div className="relative" style={{ height }}>
          {state.phase === 'ready' && frameDoc ? (
            <iframe
              srcDoc={frameDoc}
              title={title ?? `${taskId} artifact generated by ${modelId}`}
              className="h-full w-full border-0 bg-[#0c0c10]"
              // No allow-same-origin: the srcdoc runs at an opaque origin, so
              // allow-scripts alone keeps model-generated JS walled off.
              sandbox="allow-scripts"
            />
          ) : state.phase === 'error' ? (
            <div className="flex h-full flex-col items-center justify-center p-8 text-center">
              <AlertCircle className="h-8 w-8 text-rose-500" aria-hidden />
              <p className="mt-3 text-sm text-white/80">Couldn’t load this artifact.</p>
              <p className="mt-1 font-mono text-xs text-white/50">{state.message}</p>
              <button
                type="button"
                onClick={run}
                className="mt-4 inline-flex items-center gap-2 rounded-lg border border-white/15 bg-white/5 px-4 py-2 text-sm font-medium text-white/85 transition-colors hover:bg-white/10"
              >
                <Play className="h-3.5 w-3.5" aria-hidden />
                Retry
              </button>
            </div>
          ) : state.phase === 'loading' ? (
            <div
              className="flex h-full flex-col items-center justify-center gap-3"
              aria-label="Loading artifact"
            >
              <div className="flex items-center gap-1.5">
                <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-white/60 [animation-delay:0ms] motion-reduce:animate-none" />
                <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-white/60 [animation-delay:200ms] motion-reduce:animate-none" />
                <span className="h-1.5 w-1.5 animate-pulse rounded-full bg-white/60 [animation-delay:400ms] motion-reduce:animate-none" />
              </div>
              <div className="flex items-center gap-2 font-mono text-xs uppercase tracking-wider text-white/60">
                <Loader2 className="h-3.5 w-3.5 animate-spin motion-reduce:animate-none" aria-hidden />
                Loading artifact
              </div>
            </div>
          ) : (
            <div className="flex h-full flex-col items-center justify-center p-8 text-center">
              <Play className="h-8 w-8 text-white/50" aria-hidden />
              <p className="mt-3 text-sm text-white/80">Run this model’s artifact</p>
              <p className="mt-1 max-w-xs text-xs text-white/50">
                Renders live in a sandboxed frame. It won’t start until you press run.
              </p>
              <button
                type="button"
                onClick={run}
                className="mt-4 inline-flex items-center gap-2 rounded-lg border border-white/15 bg-white/5 px-4 py-2 text-sm font-medium text-white/85 transition-colors hover:bg-white/10"
              >
                <Play className="h-3.5 w-3.5" aria-hidden />
                Run demo
              </button>
            </div>
          )}
        </div>
      </div>
      <figcaption className="mt-3 flex flex-wrap items-baseline justify-between gap-x-4 gap-y-1 text-sm text-muted">
        <span>{caption}</span>
        <a
          href={outputHtmlUrl(taskId, modelId, version)}
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex shrink-0 items-center gap-1.5 text-project underline underline-offset-4 decoration-project/40 transition-colors hover:decoration-project"
        >
          Open full page
          <ExternalLink className="h-3.5 w-3.5" aria-hidden />
        </a>
      </figcaption>
    </figure>
  )
}

// Client-only, mirroring the BlackHoleSim embed: the fetch + sandboxed frame
// never block the static post render, and the chunk is requested once.
const ArtifactFrameLazy = dynamic(() => Promise.resolve(ArtifactFrameInner), {
  ssr: false,
  loading: () => (
    <div
      className="h-[480px] w-full animate-pulse rounded-xl border border-[var(--color-border)]"
      style={{ background: '#0c0c10' }}
      aria-hidden
    />
  ),
})

/**
 * `<ArtifactFrame />` — embeds one artifact from the site's LLM benchmark
 * (/lab/llm-benchmark/) inside a post: the output JSON is fetched from
 * /lab-data/llm-benchmark/outputs on mount and run live in a sandboxed
 * srcdoc iframe, with an "Open full page" escape hatch below.
 */
export function ArtifactFrame(props: ArtifactFrameProps) {
  return (
    <div className="not-prose my-8">
      <ArtifactFrameLazy {...props} />
    </div>
  )
}
