import type { Hike } from '@/lib/gen/content'

/**
 * Hiking section content. Stats and routes are DRAFTS — approximate figures and
 * stylized (non-geographic) waypoint coordinates meant to evoke each route's
 * shape on the bespoke journey map. Verify the numbers and tweak waypoint
 * x/y (normalized 0..1) to taste. Photos are managed separately via the admin
 * console (per-hike manifest.json in the GCS bucket); galleries fall back to
 * placeholders until images are added.
 */
export const hikes: Hike[] = [
  // ── Completed (most recent first) ─────────────────────────────────────────
  {
    slug: 'dolomites-alta-via-1',
    name: 'Alta Via 1',
    region: 'The Dolomites',
    country: 'Italy',
    status: 'completed',
    year: '2025',
    dates: '2025',
    accent: '#7c93c9',
    summary:
      'The classic high route through the Dolomites — Lago di Braies south to Belluno, hut to hut beneath the pale vertical walls and across high cols, a string of rifugios stitched between limestone cathedrals.',
    distanceKm: 120,
    days: 10,
    elevationGainM: 6500,
    maxAltitudeM: 2752,
    highlights: ['Lago di Braies at dawn', 'Lagazuoi & the WWI tunnels', 'Cinque Torri', 'Civetta’s great wall'],
    order: 1,
    hero: '/hiking/art/dolomites-alta-via-1.webp',
    waypoints: [
      { name: 'Lago di Braies', x: 0.5, y: 0.07, elev: 1496, day: 'Day 1', note: 'The turquoise lake start.' },
      { name: 'Rifugio Fanes', x: 0.43, y: 0.22, elev: 2060, day: 'Day 2', note: '' },
      { name: 'Lagazuoi', x: 0.57, y: 0.34, elev: 2752, day: 'Day 3', note: 'High point; WWI front-line tunnels.' },
      { name: 'Cinque Torri', x: 0.47, y: 0.46, elev: 2137, day: 'Day 4', note: 'Five towers of rock.' },
      { name: 'Rifugio Coldai', x: 0.55, y: 0.58, elev: 2132, day: 'Day 5', note: '' },
      { name: 'Civetta', x: 0.45, y: 0.7, elev: 2000, day: 'Day 6', note: 'The great 1000 m wall.' },
      { name: 'Rifugio Pramperet', x: 0.53, y: 0.82, elev: 1857, day: 'Day 8', note: '' },
      { name: 'Belluno', x: 0.5, y: 0.93, elev: 390, day: 'Day 10', note: 'Down into the valley.' },
    ],
  },
  {
    slug: 'larapinta-trail',
    name: 'Larapinta Trail',
    region: 'West MacDonnell Ranges',
    country: 'Australia · NT',
    status: 'completed',
    year: '2025',
    dates: '2025',
    accent: '#c2693a',
    summary:
      'End to end along the spine of the West MacDonnell Ranges — Alice Springs Telegraph Station west to Mt Sonder. Red quartzite ridgelines, hidden gorges and waterholes, and the desert sky at night.',
    distanceKm: 223,
    days: 14,
    elevationGainM: 6500,
    maxAltitudeM: 1380,
    highlights: ['Mt Sonder sunrise', 'Counts Point ridge', 'Ormiston Gorge', 'Standley Chasm'],
    order: 2,
    hero: '/hiking/art/larapinta-trail.webp',
    waypoints: [
      { name: 'Telegraph Station', x: 0.92, y: 0.5, elev: 580, day: 'Day 1', note: 'Alice Springs start.' },
      { name: 'Simpsons Gap', x: 0.8, y: 0.44, elev: 620, day: 'Day 2', note: '' },
      { name: 'Standley Chasm', x: 0.68, y: 0.56, elev: 680, day: 'Day 4', note: '' },
      { name: 'Hugh Gorge', x: 0.56, y: 0.42, elev: 750, day: 'Day 6', note: '' },
      { name: 'Ellery Creek', x: 0.45, y: 0.56, elev: 640, day: 'Day 8', note: 'Big waterhole.' },
      { name: 'Ormiston Gorge', x: 0.31, y: 0.46, elev: 720, day: 'Day 11', note: '' },
      { name: 'Redbank Gorge', x: 0.18, y: 0.54, elev: 780, day: 'Day 13', note: '' },
      { name: 'Mt Sonder', x: 0.08, y: 0.4, elev: 1380, day: 'Day 14', note: 'Sunrise on the final summit.' },
    ],
  },
  {
    slug: 'overland-track',
    name: 'Overland Track',
    region: 'Cradle Mtn – Lake St Clair',
    country: 'Australia · Tasmania',
    status: 'completed',
    year: '2024',
    dates: '2024',
    accent: '#5b8c5a',
    summary:
      'Through the heart of the Tasmanian wilderness — Cradle Mountain south to Lake St Clair. Button-grass moorland, glacial tarns, rainforest and waterfalls, with side trips up Tasmania’s highest peaks.',
    distanceKm: 65,
    days: 6,
    elevationGainM: 2500,
    maxAltitudeM: 1617,
    highlights: ['Cradle Mountain', 'Mt Ossa summit (1617 m)', 'Barn Bluff', 'Waterfall side trips'],
    order: 3,
    hero: '/hiking/art/overland-track.webp',
    waypoints: [
      { name: 'Ronny Creek', x: 0.5, y: 0.08, elev: 900, day: 'Day 1', note: 'Cradle Valley start.' },
      { name: 'Waterfall Valley', x: 0.44, y: 0.22, elev: 1100, day: 'Day 1', note: 'Below Barn Bluff.' },
      { name: 'Lake Windermere', x: 0.56, y: 0.34, elev: 1000, day: 'Day 2', note: '' },
      { name: 'Pelion Plains', x: 0.47, y: 0.48, elev: 860, day: 'Day 3', note: 'Mt Ossa side trip.' },
      { name: 'Kia Ora', x: 0.55, y: 0.6, elev: 1000, day: 'Day 4', note: '' },
      { name: 'Bert Nichols Hut', x: 0.45, y: 0.72, elev: 950, day: 'Day 5', note: 'Waterfall circuit.' },
      { name: 'Narcissus', x: 0.53, y: 0.84, elev: 740, day: 'Day 6', note: '' },
      { name: 'Lake St Clair', x: 0.5, y: 0.93, elev: 750, day: 'Day 6', note: 'Australia’s deepest lake.' },
    ],
  },
  {
    slug: 'haute-route',
    name: 'Walker’s Haute Route',
    region: 'Mont Blanc → Pennine Alps',
    country: 'France → Switzerland',
    status: 'completed',
    year: '2023',
    dates: '2023',
    accent: '#4f9d8f',
    summary:
      'The great traverse from the foot of Mont Blanc to the foot of the Matterhorn — Chamonix to Zermatt on foot, crossing high passes between the two most storied peaks of the Alps.',
    distanceKm: 180,
    days: 12,
    elevationGainM: 12000,
    maxAltitudeM: 2987,
    highlights: ['Finishing under the Matterhorn', 'Col de Sorebois', 'Europe’s high passes', 'Glacier views daily'],
    order: 4,
    hero: '/hiking/art/haute-route.webp',
    waypoints: [
      { name: 'Chamonix', x: 0.06, y: 0.55, elev: 1035, day: 'Day 1', note: 'Beneath Mont Blanc.' },
      { name: 'Trient', x: 0.2, y: 0.42, elev: 1300, day: 'Day 2', note: '' },
      { name: 'Champex', x: 0.33, y: 0.56, elev: 1466, day: 'Day 3', note: '' },
      { name: 'Le Châble', x: 0.45, y: 0.46, elev: 821, day: 'Day 4', note: '' },
      { name: 'Arolla', x: 0.58, y: 0.58, elev: 1998, day: 'Day 6', note: '' },
      { name: 'Zinal', x: 0.71, y: 0.44, elev: 1675, day: 'Day 8', note: '' },
      { name: 'Gruben', x: 0.82, y: 0.56, elev: 1822, day: 'Day 10', note: '' },
      { name: 'Zermatt', x: 0.93, y: 0.42, elev: 1620, day: 'Day 12', note: 'The Matterhorn finish.' },
    ],
  },

  // ── Planned ───────────────────────────────────────────────────────────────
  {
    slug: 'inca-trail',
    name: 'Inca Trail to Machu Picchu',
    region: 'Andes · Sacred Valley',
    country: 'Peru',
    status: 'planned',
    year: 'planned',
    dates: '',
    accent: '#c79a4b',
    summary:
      'The original royal road to Machu Picchu — Inca stone stairways over high passes and through cloud forest, arriving at the Sun Gate above the lost city at dawn.',
    distanceKm: 43,
    days: 4,
    elevationGainM: 2200,
    maxAltitudeM: 4215,
    highlights: ['Dead Woman’s Pass (4,215 m)', 'Sun Gate at sunrise', 'Cloud-forest ruins', 'Machu Picchu'],
    order: 1,
    hero: '/hiking/art/inca-trail.webp',
    waypoints: [
      { name: 'KM82 · Piscacucho', x: 0.86, y: 0.7, elev: 2600, day: 'Day 1', note: 'Trailhead.' },
      { name: 'Llactapata', x: 0.72, y: 0.62, elev: 2650, day: 'Day 1', note: '' },
      { name: 'Dead Woman’s Pass', x: 0.55, y: 0.36, elev: 4215, day: 'Day 2', note: 'The high point.' },
      { name: 'Pacaymayo', x: 0.46, y: 0.5, elev: 3600, day: 'Day 2', note: '' },
      { name: 'Phuyupatamarca', x: 0.3, y: 0.5, elev: 3680, day: 'Day 3', note: '' },
      { name: 'Wiñay Wayna', x: 0.2, y: 0.6, elev: 2680, day: 'Day 3', note: '' },
      { name: 'Machu Picchu', x: 0.1, y: 0.46, elev: 2430, day: 'Day 4', note: 'Through the Sun Gate.' },
    ],
  },
  {
    slug: 'tour-du-mont-blanc',
    name: 'Tour du Mont Blanc',
    region: 'Mont Blanc massif',
    country: 'France · Italy · Switzerland',
    status: 'planned',
    year: 'planned',
    dates: '',
    accent: '#5aa0b5',
    summary:
      'The full circuit of the Mont Blanc massif — a loop through three countries, around the highest mountain in the Alps, over a chain of high cols with the summit never far from view.',
    distanceKm: 170,
    days: 11,
    elevationGainM: 10000,
    maxAltitudeM: 2665,
    highlights: ['Three countries on foot', 'Col de la Seigne', 'Grand Col Ferret', 'Rifugio Bonatti'],
    order: 2,
    hero: '/hiking/art/tour-du-mont-blanc.webp',
    waypoints: [
      { name: 'Les Houches', x: 0.22, y: 0.5, elev: 1000, day: 'Day 1', note: 'Start & finish.' },
      { name: 'Les Contamines', x: 0.32, y: 0.72, elev: 1160, day: 'Day 2', note: '' },
      { name: 'Les Chapieux', x: 0.5, y: 0.82, elev: 1550, day: 'Day 3', note: '' },
      { name: 'Courmayeur', x: 0.7, y: 0.74, elev: 1224, day: 'Day 5', note: 'Italy.' },
      { name: 'Rifugio Bonatti', x: 0.82, y: 0.54, elev: 2025, day: 'Day 6', note: '' },
      { name: 'La Fouly', x: 0.76, y: 0.34, elev: 1600, day: 'Day 7', note: 'Switzerland.' },
      { name: 'Champex', x: 0.6, y: 0.22, elev: 1466, day: 'Day 8', note: '' },
      { name: 'Trient', x: 0.4, y: 0.24, elev: 1300, day: 'Day 9', note: '' },
      { name: 'Les Houches', x: 0.24, y: 0.42, elev: 1000, day: 'Day 11', note: 'Loop closed.' },
    ],
  },
  {
    slug: 'everest-base-camp',
    name: 'Everest Base Camp',
    region: 'Khumbu · Himalaya',
    country: 'Nepal',
    status: 'planned',
    year: 'planned',
    dates: '',
    accent: '#6f9fd8',
    summary:
      'Up the Khumbu valley to the foot of the highest mountain on Earth — Lukla to Base Camp, acclimatising through Sherpa villages and monasteries, to the viewpoint of Kala Patthar at 5,644 m.',
    distanceKm: 130,
    days: 12,
    elevationGainM: 5500,
    maxAltitudeM: 5644,
    highlights: ['Kala Patthar (5,644 m)', 'Namche Bazaar', 'Tengboche Monastery', 'Everest Base Camp'],
    order: 3,
    hero: '/hiking/art/everest-base-camp.webp',
    waypoints: [
      { name: 'Lukla', x: 0.5, y: 0.92, elev: 2860, day: 'Day 1', note: 'The mountain airstrip.' },
      { name: 'Namche Bazaar', x: 0.45, y: 0.78, elev: 3440, day: 'Day 2', note: 'Acclimatise.' },
      { name: 'Tengboche', x: 0.55, y: 0.64, elev: 3860, day: 'Day 4', note: 'Monastery.' },
      { name: 'Dingboche', x: 0.48, y: 0.5, elev: 4410, day: 'Day 5', note: '' },
      { name: 'Lobuche', x: 0.53, y: 0.36, elev: 4940, day: 'Day 7', note: '' },
      { name: 'Gorak Shep', x: 0.47, y: 0.24, elev: 5160, day: 'Day 8', note: '' },
      { name: 'Everest Base Camp', x: 0.57, y: 0.16, elev: 5364, day: 'Day 8', note: '' },
      { name: 'Kala Patthar', x: 0.44, y: 0.09, elev: 5644, day: 'Day 9', note: 'The viewpoint.' },
    ],
  },
  {
    slug: 'torres-del-paine-o',
    name: 'Torres del Paine · O Circuit',
    region: 'Patagonia',
    country: 'Chile',
    status: 'planned',
    year: 'planned',
    dates: '',
    accent: '#6cb3a0',
    summary:
      'The full loop around the Paine massif — the wild back side over the John Gardner Pass above Grey Glacier, then the famous W, finishing under the granite towers at first light.',
    distanceKm: 130,
    days: 8,
    elevationGainM: 5000,
    maxAltitudeM: 1200,
    highlights: ['John Gardner Pass', 'Grey Glacier', 'Valle del Francés', 'The Towers at sunrise'],
    order: 4,
    hero: '/hiking/art/torres-del-paine-o.webp',
    waypoints: [
      { name: 'Central', x: 0.5, y: 0.78, elev: 80, day: 'Day 1', note: 'Start of the loop.' },
      { name: 'Serón', x: 0.64, y: 0.6, elev: 150, day: 'Day 1', note: '' },
      { name: 'Dickson', x: 0.6, y: 0.4, elev: 250, day: 'Day 2', note: '' },
      { name: 'Los Perros', x: 0.5, y: 0.28, elev: 600, day: 'Day 3', note: '' },
      { name: 'John Gardner Pass', x: 0.38, y: 0.2, elev: 1200, day: 'Day 4', note: 'High point, Grey Glacier below.' },
      { name: 'Grey', x: 0.3, y: 0.36, elev: 80, day: 'Day 4', note: '' },
      { name: 'Paine Grande', x: 0.36, y: 0.52, elev: 50, day: 'Day 5', note: '' },
      { name: 'Valle del Francés', x: 0.46, y: 0.62, elev: 400, day: 'Day 6', note: '' },
      { name: 'Las Torres', x: 0.58, y: 0.72, elev: 850, day: 'Day 8', note: 'Sunrise at the towers.' },
    ],
  },
  {
    slug: 'kungsleden',
    name: 'Kungsleden · The King’s Trail',
    region: 'Arctic Lapland',
    country: 'Sweden',
    status: 'planned',
    year: 'planned',
    dates: '',
    accent: '#8fae6b',
    summary:
      'The northern stretch of Sweden’s King’s Trail — Abisko to Nikkaluokta through Arctic tundra above the tree line, past Sweden’s highest mountain, in the land of the midnight sun.',
    distanceKm: 105,
    days: 7,
    elevationGainM: 2600,
    maxAltitudeM: 1150,
    highlights: ['Tjäktja Pass', 'Kebnekaise (side ascent, 2,096 m)', 'Arctic tundra', 'Midnight sun'],
    order: 5,
    hero: '/hiking/art/kungsleden.webp',
    waypoints: [
      { name: 'Abisko', x: 0.5, y: 0.08, elev: 385, day: 'Day 1', note: 'Trailhead by the lake.' },
      { name: 'Abiskojaure', x: 0.45, y: 0.22, elev: 490, day: 'Day 1', note: '' },
      { name: 'Alesjaure', x: 0.55, y: 0.34, elev: 800, day: 'Day 2', note: '' },
      { name: 'Tjäktja Pass', x: 0.5, y: 0.46, elev: 1150, day: 'Day 3', note: 'High point.' },
      { name: 'Sälka', x: 0.45, y: 0.58, elev: 840, day: 'Day 4', note: '' },
      { name: 'Singi', x: 0.53, y: 0.7, elev: 780, day: 'Day 5', note: 'Kebnekaise junction.' },
      { name: 'Kebnekaise', x: 0.42, y: 0.8, elev: 700, day: 'Day 6', note: 'Sweden’s highest, side ascent.' },
      { name: 'Nikkaluokta', x: 0.5, y: 0.92, elev: 470, day: 'Day 7', note: '' },
    ],
  },
  {
    slug: 'gr20',
    name: 'GR20',
    region: 'Corsica',
    country: 'France',
    status: 'planned',
    year: 'planned',
    dates: '',
    accent: '#c98a4b',
    summary:
      'Often called the toughest trail in Europe — the high traverse of Corsica north to south, along a jagged granite spine of scrambles, slabs and exposed ridgelines between the sea and the sky.',
    distanceKm: 180,
    days: 15,
    elevationGainM: 12000,
    maxAltitudeM: 2607,
    highlights: ['Cirque de la Solitude country', 'Granite scrambling', 'Monte Cinto (side, 2,706 m)', 'Sea-to-sea spine'],
    order: 6,
    hero: '/hiking/art/gr20.webp',
    waypoints: [
      { name: 'Calenzana', x: 0.5, y: 0.07, elev: 275, day: 'Day 1', note: 'Northern trailhead.' },
      { name: 'Carozzu', x: 0.45, y: 0.18, elev: 1270, day: 'Day 2', note: '' },
      { name: 'Ascu Stagnu', x: 0.55, y: 0.28, elev: 1422, day: 'Day 3', note: 'Monte Cinto side.' },
      { name: 'Tighjettu', x: 0.48, y: 0.38, elev: 1683, day: 'Day 4', note: '' },
      { name: 'Castel di Vergio', x: 0.53, y: 0.5, elev: 1404, day: 'Day 6', note: '' },
      { name: 'Manganu', x: 0.46, y: 0.6, elev: 1601, day: 'Day 7', note: '' },
      { name: 'Petra Piana', x: 0.54, y: 0.68, elev: 1842, day: 'Day 8', note: '' },
      { name: 'Vizzavona', x: 0.48, y: 0.8, elev: 910, day: 'Day 9', note: 'The midpoint town.' },
      { name: 'Conca', x: 0.5, y: 0.93, elev: 250, day: 'Day 15', note: 'Southern finish.' },
    ],
  },
]

export const completedHikes = hikes.filter((h) => h.status === 'completed').sort((a, b) => a.order - b.order)
export const plannedHikes = hikes.filter((h) => h.status === 'planned').sort((a, b) => a.order - b.order)
export const getHike = (slug: string) => hikes.find((h) => h.slug === slug)
