import type { Circuit, CircuitComponent, CircuitWire, ComponentType, WaveformKind } from './types'

export function serializeCircuit(circuit: Circuit): string {
  const lines: string[] = [
    '# Circuit Simulator Design',
    '# Generated by benebsworth.com/lab/circuit-sim',
    'version: 1',
    `nextNodeId: ${circuit.nextNodeId}`,
    `nextCompId: ${circuit.nextCompId}`,
    'components:',
  ]

  for (const c of circuit.components) {
    lines.push(`  - id: ${c.id}`)
    lines.push(`    type: ${c.type}`)
    lines.push(`    value: ${c.value}`)
    lines.push(`    nodeA: ${c.nodeA}`)
    lines.push(`    nodeB: ${c.nodeB}`)
    lines.push(`    x: ${c.x}`)
    lines.push(`    y: ${c.y}`)
    lines.push(`    rotation: ${c.rotation}`)
    if (c.waveform) {
      lines.push(`    wkind: ${c.waveform.kind}`)
      lines.push(`    wamp: ${c.waveform.amplitude}`)
      lines.push(`    woff: ${c.waveform.offset}`)
      lines.push(`    wfreq: ${c.waveform.freq}`)
      lines.push(`    wphase: ${c.waveform.phase}`)
      lines.push(`    wduty: ${c.waveform.duty}`)
    }
    if (c.acMag !== undefined) lines.push(`    acmag: ${c.acMag}`)
    if (c.type === 'SW') lines.push(`    closed: ${c.closed ? 'true' : 'false'}`)
  }

  lines.push('wires:')
  for (const w of circuit.wires) {
    lines.push(`  - id: ${w.id}`)
    lines.push(`    nodeA: ${w.nodeA}`)
    lines.push(`    nodeB: ${w.nodeB}`)
    lines.push(`    waypoints: ${serializeWaypoints(w.waypoints)}`)
  }

  return lines.join('\n') + '\n'
}

function serializeWaypoints(waypoints: { x: number; y: number }[]): string {
  if (waypoints.length === 0) return '[]'
  return '[' + waypoints.map(wp => `${wp.x},${wp.y}`).join(' ') + ']'
}

export function deserializeCircuit(yaml: string): Circuit {
  const lines = yaml.split('\n')
  let nextNodeId = 1
  let nextCompId = 1
  const components: CircuitComponent[] = []
  const wires: CircuitWire[] = []

  let i = 0
  let currentComponent: Partial<CircuitComponent> | null = null
  let currentWire: Partial<CircuitWire> | null = null
  let inComponents = false
  let inWires = false

  function finalizeComponent() {
    if (currentComponent && currentComponent.id && currentComponent.type) {
      const cc = currentComponent as Record<string, unknown>
      if (typeof cc.wkind === 'string') {
        currentComponent.waveform = {
          kind: cc.wkind as WaveformKind,
          amplitude: num(cc.wamp, 0),
          offset: num(cc.woff, 0),
          freq: num(cc.wfreq, 0),
          phase: num(cc.wphase, 0),
          duty: num(cc.wduty, 0.5),
        }
      }
      if (cc.acmag !== undefined) currentComponent.acMag = num(cc.acmag, 1)
      for (const k of ['wkind', 'wamp', 'woff', 'wfreq', 'wphase', 'wduty', 'acmag']) delete cc[k]
      components.push(currentComponent as CircuitComponent)
    }
    currentComponent = null
  }

  function finalizeWire() {
    if (currentWire && currentWire.id) {
      currentWire.waypoints = currentWire.waypoints ?? []
      wires.push(currentWire as CircuitWire)
    }
    currentWire = null
  }

  while (i < lines.length) {
    const raw = lines[i]
    const trimmed = raw.trimStart()
    if (trimmed === '' || trimmed.startsWith('#')) { i++; continue }

    const indent = raw.length - trimmed.length

    if (indent === 0) {
      // Top-level key
      finalizeComponent()
      finalizeWire()
      inComponents = false
      inWires = false

      const [key, ...rest] = trimmed.split(':')
      const value = rest.join(':').trim()

      if (key === 'version') { /* skip */ }
      else if (key === 'nextNodeId') nextNodeId = parseInt(value, 10)
      else if (key === 'nextCompId') nextCompId = parseInt(value, 10)
      else if (key === 'components') { inComponents = true }
      else if (key === 'wires') { inWires = true }
    } else if (indent === 2 && inComponents && trimmed.startsWith('- ')) {
      finalizeComponent()
      const firstKV = trimmed.slice(2)
      const [k, ...rest] = firstKV.split(':')
      const v = rest.join(':').trim()
      currentComponent = { [k.trim()]: parseValue(k.trim() as keyof CircuitComponent, v) }
    } else if (indent === 4 && inComponents && currentComponent) {
      const [k, ...rest] = trimmed.split(':')
      const v = rest.join(':').trim()
      ;(currentComponent as Record<string, unknown>)[k.trim()] = parseValue(k.trim() as keyof CircuitComponent, v)
    } else if (indent === 2 && inWires && trimmed.startsWith('- ')) {
      finalizeWire()
      const firstKV = trimmed.slice(2)
      const [k, ...rest] = firstKV.split(':')
      const v = rest.join(':').trim()
      currentWire = { [k.trim()]: parseWireValue(k.trim(), v) }
    } else if (indent === 4 && inWires && currentWire) {
      const [k, ...rest] = trimmed.split(':')
      const v = rest.join(':').trim()
      ;(currentWire as Record<string, unknown>)[k.trim()] = parseWireValue(k.trim(), v)
    }

    i++
  }

  finalizeComponent()
  finalizeWire()

  return { components, wires, nextNodeId, nextCompId }
}

function parseValue(key: string, raw: string): unknown {
  switch (key) {
    case 'id': return raw
    case 'type': return raw as ComponentType
    case 'value': return parseFloat(raw)
    case 'nodeA':
    case 'nodeB': return parseInt(raw, 10)
    case 'x':
    case 'y': return parseInt(raw, 10)
    case 'rotation': return parseInt(raw, 10) as 0 | 90 | 180 | 270
    case 'wamp':
    case 'woff':
    case 'wfreq':
    case 'wphase':
    case 'wduty':
    case 'acmag': return parseFloat(raw)
    case 'wkind': return raw
    case 'closed': return raw === 'true'
    default: return raw
  }
}

function num(v: unknown, fallback: number): number {
  return typeof v === 'number' && isFinite(v) ? v : fallback
}

function parseWireValue(key: string, raw: string): unknown {
  switch (key) {
    case 'id': return raw
    case 'nodeA':
    case 'nodeB': return parseInt(raw, 10)
    case 'waypoints': return parseWaypoints(raw)
    default: return raw
  }
}

function parseWaypoints(raw: string): { x: number; y: number }[] {
  const inner = raw.replace(/^\[|\]$/g, '').trim()
  if (inner === '') return []
  return inner.split(/\s+/).map(pair => {
    const [x, y] = pair.split(',').map(Number)
    return { x, y }
  })
}
