import { notFound } from 'next/navigation'
import type { Metadata } from 'next'
import { getPublishedPosts, getPost, isPublished } from '@/lib/content'
import { topicFor } from '@/lib/topics'
import { MdxContent } from '@/components/mdx/mdx-content'
import { TopicMarker } from '@/components/blog/topic-marker'
import { SiteNav } from '@/components/site/site-nav'
import { SiteFooter } from '@/components/site/site-footer'
import { Breadcrumb } from '@/components/site/breadcrumb'
import { tagColor } from '@/lib/tag-colors'
import { TableOfContents } from '@/components/blog/table-of-contents'
import { RelatedLabs } from '@/components/blog/related-labs'
import { RelatedPosts } from '@/components/blog/related-posts'
import { MobileToc } from '@/components/blog/mobile-toc'
import { JsonLd, SITE_URL, breadcrumbLd } from '@/components/seo/json-ld'
import { fmtDate } from '@/lib/format'

export function generateStaticParams() {
  return getPublishedPosts().map((p) => ({ slug: p.slug }))
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }): Promise<Metadata> {
  const { slug } = await params
  const p = getPost(slug)
  if (!p || !isPublished(p)) return { title: 'Not found' }
  const topic = topicFor(p)
  const url = `/blog/${slug}/`
  return {
    title: p.title,
    description: p.description,
    keywords: p.tags,
    // rel="alternate" type="text/markdown" → tells LLM crawlers (GPTBot,
    // ClaudeBot, PerplexityBot, etc.) and SEO tools that a plain-Markdown
    // sibling is available at this URL. Generated by scripts/gen-md-siblings.mjs.
    alternates: {
      canonical: url,
      types: { 'text/markdown': `${url}index.md` },
    },
    openGraph: {
      type: 'article',
      title: p.title,
      description: p.description,
      url,
      siteName: 'Ben Ebsworth',
      locale: 'en_AU',
      publishedTime: new Date(p.date).toISOString(),
      modifiedTime: new Date(p.date).toISOString(),
      authors: ['Ben Ebsworth'],
      tags: p.tags,
      section: topic.label,
    },
    twitter: {
      card: 'summary_large_image',
      title: p.title,
      description: p.description,
      creator: '@benebsworth',
      site: '@benebsworth',
    },
  }
}

export default async function PostPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params
  const p = getPost(slug)
  if (!p || !isPublished(p)) notFound()
  const topic = topicFor(p)
  const url = `${SITE_URL}/blog/${slug}/`
  const published = new Date(p.date).toISOString()
  // Word count is a small but useful SEO signal — search engines use it
  // for content-depth heuristics. The body is MDX so we strip JSX-ish
  // constructs (LaTeX blocks, component tags) before counting.
  const wordCount = p.body
    .replace(/```[\s\S]*?```/g, ' ') // code blocks
    .replace(/<[^>]+>/g, ' ')        // JSX tags
    .replace(/\$\$[\s\S]*?\$\$/g, ' ') // display math
    .replace(/\$[^$]+\$/g, ' ')     // inline math
    .replace(/[#*_`>~|]/g, ' ')     // markdown punctuation
    .split(/\s+/)
    .filter(Boolean).length
  const readingTime = Math.max(1, Math.round(wordCount / 230))
  // High-level article section for Google's News / Discover box. We use
  // the topic label (e.g. "Algorithms", "Service Mesh") which is also
  // the visual badge at the top of the post.
  const articleSection = topic.label
  const blogPostingLd = {
    '@context': 'https://schema.org',
    '@type': 'BlogPosting',
    headline: p.title,
    description: p.description,
    datePublished: published,
    dateModified: published,
    inLanguage: 'en-AU',
    articleSection,
    wordCount,
    author: {
      '@type': 'Person',
      name: 'Ben Ebsworth',
      url: `${SITE_URL}/about/`,
      // SameAs: github profile, in addition to those in the global
      // Person schema on the home/about pages. Helps Google build the
      // author entity graph.
      sameAs: ['https://github.com/castlemilk'],
    },
    publisher: {
      '@type': 'Person',
      name: 'Ben Ebsworth',
      url: SITE_URL,
    },
    image: {
      '@type': 'ImageObject',
      url: `${url}opengraph-image`,
      width: 1200,
      height: 630,
    },
    mainEntityOfPage: { '@type': 'WebPage', '@id': url },
    url,
    ...(p.tags.length ? { keywords: p.tags.join(', ') } : {}),
  }
  const breadcrumb = breadcrumbLd([
    { name: 'Home', url: `${SITE_URL}/` },
    { name: 'Blog', url: `${SITE_URL}/blog/` },
    { name: p.title, url },
  ])
  return (
    <>
      <JsonLd data={[blogPostingLd, breadcrumb]} />
      {p.heroImage && (
        <link rel="preload" as="image" href={p.heroImage} fetchPriority="high" />
      )}
      <SiteNav />
      {/* Sticky breadcrumb sits just below the sticky SiteNav. */}
      <Breadcrumb
        className="mb-0"
        items={[{ label: 'Home', href: '/' }, { label: 'Blog', href: '/blog/' }, { label: p.title }]}
      />
      {/* Two-column layout on lg+: the article (capped at 44rem reading
          measure) on the left, and the sticky TOC on the right. The
          post's own `pt-8` on <main> still creates the right breathing
          room because sticky elements stay in normal flow. */}
      <main id="main-content" className="mx-auto w-full max-w-6xl px-6 pb-32 pt-6 sm:px-8 md:pt-8">
        <div className="grid gap-10 lg:grid-cols-[minmax(0,1fr)_14rem] xl:grid-cols-[minmax(0,1fr)_16rem]">
          <article className="min-w-0">
        {/* ── Post header spans the full (wide) page frame — editorial title +
            accent rule fill the screen. Only the long-form prose below is capped
            to a comfortable reading measure (~44rem ≈ 74ch). ── */}
        <header className="relative">
          {/* soft topic-tinted wash behind the title */}
          <span
            aria-hidden
            className="pointer-events-none absolute -top-12 left-0 -z-10 h-40 w-full opacity-70 blur-3xl"
            style={{
              background: `radial-gradient(60% 100% at 0% 0%, color-mix(in srgb, ${topic.accent} 16%, transparent), transparent 70%)`,
            }}
          />
          <div className="flex flex-wrap items-center gap-x-4 gap-y-2">
            <TopicMarker topic={topic} />
            <div className="flex flex-wrap items-center gap-2">
              <time className="font-mono text-[0.7rem] uppercase tracking-[0.18em] text-muted">
                {fmtDate(p.date)}
              </time>
              <span className="font-mono text-[0.7rem] uppercase tracking-[0.18em] text-muted">
                · {readingTime} min read · Ben Ebsworth
              </span>
            </div>
          </div>
          <h1 className="type-h1 mt-5">
            {p.title}
          </h1>
          {p.description && (
            <p className="mt-4 max-w-2xl font-sans text-lg leading-8 text-fg/65">
              {p.description}
            </p>
          )}
          {p.tags.length > 0 && (
            <div className="mt-4 flex flex-wrap gap-1.5">
              {p.tags.slice(0, 6).map((t) => {
                const c = tagColor(t)
                return (
                  <span
                    key={t}
                    className="accent-ink rounded-full border px-2 py-0.5 font-mono text-[0.55rem] uppercase tracking-wider"
                    style={{
                      '--ink': c,
                      borderColor: `color-mix(in srgb, ${c} 40%, transparent)`,
                      backgroundColor: `color-mix(in srgb, ${c} 14%, transparent)`,
                    } as React.CSSProperties}
                  >
                    {t}
                  </span>
                )
              })}
            </div>
          )}
          {/* accent rule keyed to the topic */}
          <div
            className="mt-7 h-px w-full"
            style={{
              background: `linear-gradient(to right, ${topic.accent}, color-mix(in srgb, ${topic.accent} 8%, transparent) 60%, transparent)`,
            }}
          />
        </header>
        <div className="mt-10 max-w-[44rem]">
          <MobileToc />
          <MdxContent source={p.body} slug={p.slug} />
        </div>
          {/* "Try it in the lab" footer. Uses the post's tags to find
              matching lab effects, with a daily-rotating random fallback
              when no overlap exists. */}
          <div className="max-w-[44rem]">
            <RelatedLabs tags={p.tags} labels={p.tags} limit={3} />
            <RelatedPosts currentSlug={slug} tags={p.tags} />
          </div>
          </article>
          {/* Sticky right-rail TOC. Only visible on lg+ — mobile users
              get the in-content inline mini-map already. */}
          <aside className="hidden lg:block">
            <TableOfContents />
          </aside>
        </div>
      </main>
      <SiteFooter />
    </>
  )
}
